[package]
name = "monarch"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
skim = "0.16.0"
clap = { version = "4.5.32", features = ["derive"] }
walkdir = "2.5.0"
rootcause = "0.11.0"
thiserror = "2.0.17"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
